config/routes.rb
Rails.application.routes.draw do

  mount DtsCmsAdmin::Engine, at: "cms"

  root 'login#index'

  ##
  # Customers
  resources :clientes do
    member do
      get "pedidos"
    end
  end
  post  'clientes/seleccionar' => "clientes#seleccionar"
  get  'clientes/:id/seleccionar/:proc' => "clientes#seleccionar"

  ##
  # Orders
  resources :pedidos do
    member do
      get "confirmar"
      get "generar"
    end
  end

  ##
  # Shared
  get 'pedidos' => 'static#orders'
  get 'pedidos/:id'  => 'static#order'

  ##
  # Talleres
  get 'taller/inicio' => 'talleres#index'
  get 'taller/pedido_recibido/:id' => 'talleres#pedido_recibido'
  get 'taller/pedido_montado/:id' => 'talleres#pedido_montado'
  get 'taller/preferencias' => 'talleres#preferencias'
  get 'taller/neumaticos' => 'talleres#neumaticos'
  post 'taller/neumaticos' => 'talleres#neumaticos'
  post 'talleres/suplementos'
  get 'taller/:id/neumatico' => 'talleres#neumatico'

  ##
  # Cart
  get  'carrito' => "shopping_carts#show"
  post 'carrito/modificar/:id' => "shopping_carts#modify"
  get  'carrito/eliminar/:id' => "shopping_carts#remove"
  get  'carrito/vaciar' => "shopping_carts#clear"
  get  'carrito/guardar_como_presupuesto' => "shopping_carts#save_as_bugdet"
  get  'carrito/eliminar_presupuesto/:id' => "shopping_carts#destroy_budget"

  ##
  # acts_as_cart routes
  resource :shopping_cart


  ##
  # Proveedores

  # almacen
  get "almacen/inicio"
  get "almacen/pendientes"
  get "almacen/enviados"

  #gerencia
  get "gerencia/inicio"
  get "gerencia/listados"

  #financiero
  get "financiero/inicio"
  get "financiero/distribuidores"
  get "financiero/clientes"
  get "financiero/historico"

  #admin
  get "admin/inicio"
  get "admin/neumaticos"
  get "admin/distribuidores"
  get "admin/talleres"
  get "admin/pedidos"
  get "admin/preferencias"
  get "admin/web"
  get "admin/expedicion_listado"
  get "admin/expedicion_pendientes"
  get "admin/expedicion_enviados"

  #comercial

  get "comercial/neumaticos"
  get 'comercial/:id/neumatico' => 'comercial#neumatico'
  post "comercial/neumaticos"

  ##
  # Login

  get  "login/index"
  post "login/index"

  ##
  # Web Design
  get "web/selector"
  post "web/selector"

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :pedidos
  has_many :presupuestos
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  def index
    @clientes = Cliente.all.limit(30)
  end

  def show
  end

  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def buscar
    sugerencias = Cliente.select(:nombre_empresa).where("nombre_empresa like ?", "%#{params[:term]}%")
    render json: sugerencias
  end

  def seleccionar
    if request.post?
      cliente = Cliente.where("nombre_empresa like ?", "%#{params[:nombre]}%").first
      path = "/carrito"
    end
    if request.get?
      cliente = Cliente.find(params[:id])
      path = "/carrito" if params[:proc] == "cart"
      path = "/taller/neumaticos" if params[:proc] == "list"
    end
    session[:cliente_id] = cliente.id if cliente
    redirect_to path
  end

  def agregar

  end

  def pedidos
    @pedidos = Pedido.where(cliente_id: params[:id])
    @cliente = @pedidos.first.cliente rescue Cliente.find(params[:id])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cliente
    @cliente = Cliente.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cliente_params
    params.require(:cliente).permit(:email, :tipo_documento, :dni, :nombre_empresa, :razon_fiscal, :calle, :codigo_postal, :localidad, :provincia, :pais, :telefono, :movil, :fax, :condiciones_venta, :descuento, :fecha_alta, :riesgo)
  end
end

app/views/clientes/index.html.erb
<div class="container-fluid main-content">
  <div class="page-title">
    <h1>
      Clientes
    </h1>
  </div>
  <!-- DataTables Example -->
  <div class="row">
    <div class="col-lg-12">
      <div class="widget-container fluid-height clearfix">
        <div class="heading">
          <i class="fa fa-table"></i> Listando todos los clientes
        </div>
        <div class="widget-content padded clearfix">

          <table class="table table-bordered table-striped" id="dataTable1">
            <thead>
            <th>
              Nombre
            </th>
            <th>
              Telefono
            </th>
            <th class="hidden-xs">
              Movil
            </th>
            <th class="hidden-xs">
              Email
            </th>
            <th class="hidden-xs">

            </th>
            </thead>
            <tbody>
            <% @clientes.each do |cliente| %>
                <tr>
                  <td>
                    <%= cliente.nombre_empresa %>
                  </td>
                  <td>
                    <%= cliente.telefono %>
                  </td>
                  <td class="hidden-xs">
                    <%= cliente.movil %>
                  </td>
                  <td class="hidden-xs">
                    <%= cliente.email %>
                  </td>
                  <td class="hidden-xs">
                    <div class="btn-group">

                      <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Consulta<span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <li>
                          <%= link_to %{<i class="fa fa-shopping-cart"></i> Pedidos</a>}.html_safe, pedidos_cliente_path(cliente) %>
                        </li>
                        <li>
                          <a href="/clientes/<%= cliente.id %>/seleccionar/cart"><i class="fa fa-save"></i> Presupuestos</a>
                        </li>
                      </ul>
                    </div>

                    <a href="/clientes/<%= cliente.id %>/seleccionar/list" class="btn btn-success-outline"><i class="fa fa-shopping-cart"></i> Comprar</a>

                  </td>
                </tr>
            <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- end DataTables Example -->
</div>

app/views/clientes/pedidos.html.erb
<div class="container-fluid main-content">
  <div class="page-title">
    <h1>
      Pedidos
    </h1>
  </div>
  <!-- DataTables Example -->
  <div class="row">
    <div class="col-lg-12">
      <div class="widget-container fluid-height clearfix">
        <div class="heading">
          <i class="fa fa-table"></i> Listando los pedidos de: <%= @cliente.nombre_empresa %>
        </div>
        <div class="widget-content padded clearfix">
          <table class="table table-bordered table-striped" id="dataTable1">
            <thead>
            <th class="check-header hidden-xs">
              <label><input id="checkAll" name="checkAll" type="checkbox"><span></span></label>
            </th>
            <th>
              # Pedido
            </th>
            <th class="hidden-xs">
              Fecha
            </th>
            <th class="hidden-xs">
              Importe
            </th>
            <th class="hidden-xs">
              Estado
            </th>
            <th></th>
            </thead>
            <tbody>

            <% @pedidos.each do |pedido| %>

                <tr>
                  <td class="check hidden-xs">
                    <label><input name="optionsRadios1" type="checkbox" value="option1"><span></span></label>
                  </td>
                  <td>
                    <%= pedido.id %>
                  </td>
                  <td class="hidden-xs">
                    <%= date(pedido.fecha_alta) %>
                  </td>
                  <td class="hidden-xs">
                    <%= number_to_currency(pedido.importe, unit:'') %> €
                  </td>
                  <td class="hidden-xs">
                    <span class="label label-success">Entregado</span>
                  </td>
                  <td class="actions">
                    <div class="action-buttons">
                      <a class="table-actions" href="/pedidos/<%= pedido.id %>"><i class="fa fa-eye"></i></a>
                    </div>
                  </td>
                </tr>

            <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- end DataTables Example -->
</div>