config/routes.rb
Rails.application.routes.draw do

  mount DtsCmsAdmin::Engine, at: "cms"

  root 'login#index'

  ##
  # Customers
  resources :clientes do
    member do
      get "pedidos"
    end
  end
  post  'clientes/seleccionar' => "clientes#seleccionar"
  get  'clientes/:id/seleccionar/:proc' => "clientes#seleccionar"

  ##
  # Orders
  resources :pedidos do
    member do
      get "confirmar"
      get "generar"
    end
  end

  ##
  # Shared
  get 'pedidos' => 'static#orders'
  get 'pedidos/:id'  => 'static#order'

  ##
  # Talleres
  get 'taller/inicio' => 'talleres#index'
  get 'taller/pedido_recibido/:id' => 'talleres#pedido_recibido'
  get 'taller/pedido_montado/:id' => 'talleres#pedido_montado'
  get 'taller/preferencias' => 'talleres#preferencias'
  get 'taller/neumaticos' => 'talleres#neumaticos'
  post 'taller/neumaticos' => 'talleres#neumaticos'
  post 'talleres/suplementos'
  get 'taller/:id/neumatico' => 'talleres#neumatico'

  ##
  # Cart
  get  'carrito' => "shopping_carts#show"
  post 'carrito/modificar/:id' => "shopping_carts#modify"
  get  'carrito/eliminar/:id' => "shopping_carts#remove"
  get  'carrito/vaciar' => "shopping_carts#clear"
  get  'carrito/guardar_como_presupuesto' => "shopping_carts#save_as_bugdet"
  get  'carrito/eliminar_presupuesto/:id' => "shopping_carts#destroy_budget"

  ##
  # acts_as_cart routes
  resource :shopping_cart


  ##
  # Proveedores

  # almacen
  get "almacen/inicio"
  get "almacen/pendientes"
  get "almacen/enviados"

  #gerencia
  get "gerencia/inicio"
  get "gerencia/listados"

  #financiero
  get "financiero/inicio"
  get "financiero/distribuidores"
  get "financiero/clientes"
  get "financiero/historico"

  #admin
  get "admin/inicio"
  get "admin/neumaticos"
  get "admin/distribuidores"
  get "admin/talleres"
  get "admin/pedidos"
  get "admin/preferencias"
  get "admin/web"
  get "admin/expedicion_listado"
  get "admin/expedicion_pendientes"
  get "admin/expedicion_enviados"

  #comercial

  get "comercial/neumaticos"
  get 'comercial/:id/neumatico' => 'comercial#neumatico'
  post "comercial/neumaticos"

  ##
  # Login

  get  "login/index"
  post "login/index"

  ##
  # Web Design
  get "web/selector"
  post "web/selector"

end

app/views/admin/distribuidores.html.erb
<div class="container-fluid main-content">

  <div class="page-title chart-container">
    <h1>
      Distribuidores
    </h1>
  </div>

  <div class="col-lg-12">
    <div class="widget-container fluid-height clearfix">
      <div class="heading">
        <i class="fa fa-table"></i>Listado de Distribuidores
      </div>
      <div class="widget-content padded clearfix">
        <table class="table table-striped">
          <thead>
          <tr>
            <th></th>
            <th colspan=2 width=130>Cierre de este mes</th>
            <th colspan=2 width=130>Pendiente</th>
            <th width=65></th>
            <th width=65></th>
          </tr>
          <tr>
            <th>Nombre</th>
            <th>Cobrar</th>
            <th>Pagar</th>
            <th>Recibir</th>
            <th>Enviar</th>
            <th width="150px">Límite Concedido</th>
            <th width="150px">Cambiar límite</th>
          </tr>
          </thead>
          <tr>
            <td>Distri-1</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-2</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-3</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-4</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-5</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-6</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-7</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-8</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-9</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
          <tr>
            <td>Distri-10</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>250.000</td>
            <td class="actions">
              <div class="action-buttons">
                <a class="table-actions" href="#"><i class="fa fa-edit"></i></a>
              </div>
            </td>
          </tr>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/admin/expedicion_enviados.html.erb
<div class="container-fluid main-content">
  <div class="page-title">
    <h1>
      Neumaticos
    </h1>
  </div>
  <!-- DataTables Example -->
  <div class="row">
    <div class="col-lg-12">
      <div class="widget-container fluid-height clearfix">
        <div class="heading">
          <i class="fa fa-table"></i>Listado de los pedidos enviados
        </div>
        <div class="widget-content padded clearfix">
          <table class="table table-bordered table-striped" id="EXdataTableCatalog">
            <thead>
            <th>
              # Pedido
            </th>
            <th>
              Fecha
            </th>
            <th class="hidden-xs">
              Cliente
            </th>
            <th class="hidden-xs">
              Marca
            </th>
            <th>
              Modelo
            </th>
            <th>
              Dimensiones
            </th>
            <th>
              Unidades
            </th>
            <th>
              Acciones
            </th>
            </thead>
            <tbody>


            <% @pedidos.each do |pedido| %>

                <% pedido.pedido_detalles.each do |neumatico| %>
                    <tr>
                      <td><%= pedido.id %></td>
                      <td><%= date(pedido.fecha_alta) %></td>
                      <td><%= pedido.cliente.nombre_empresa %></td>
                      <td>
                        <%= neumatico.marca %>
                      </td>
                      <td>
                        <%= neumatico.modelo %>
                        <%= neumatico.caracteristica_1 %>
                        <%= neumatico.caracteristica_2 %>
                        <%= neumatico.caracteristica_3 %>
                      </td>
                      <td class="hidden-xs">
                        <%= neumatico.anchura %>/<%= neumatico.altura %>
                        /<%= neumatico.diametro %> <%= neumatico.carga %> <%= neumatico.velocidad %>
                      </td>
                      <td>
                        <%= neumatico.unidades %>
                      </td>
                      <td class="actions">
                        <div class="action-buttons">
                          <a class="table-actions" href="#"><i class="fa fa-check"></i></a>
                        </div>
                      </td>
                <% end %>
                </tr>
            <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- end DataTables Example -->
</div>

</div>

</div>

app/views/admin/expedicion_listado.html.erb
<div class="container-fluid main-content">
  <div class="page-title">
    <h1>
      Neumaticos
    </h1>
  </div>
  <!-- DataTables Example -->
  <div class="row">
    <div class="col-lg-12">
      <div class="widget-container fluid-height clearfix">
        <div class="heading">
          <i class="fa fa-table"></i>Listado de los Neumáticos Pendientes de expedición <a class="btn btn-sm btn-primary-outline pull-right" href="#" id="add-row" onclick="javascript:window.print();"><i class="fa fa-print"></i>Imprimir Listado</a>
        </div>
        <div class="widget-content padded clearfix">
          <table class="table table-bordered table-striped" id="EXdataTableCatalog">
            <thead>
            <th>
              # Pedido
            </th>
            <th>
              Fecha
            </th>
            <th class="hidden-xs">
              Cliente
            </th>
            <th class="hidden-xs">
              Marca
            </th>
            <th>
              Modelo
            </th>
            <th>
              Dimensiones
            </th>
            <th>
              Unidades
            </th>
            <th>
              Acciones
            </th>
            </thead>
            <tbody>

            <% @pedidos.each do |pedido| %>

                <% pedido.pedido_detalles.each do |neumatico| %>
                    <tr>
                      <td><%= pedido.id %></td>
                      <td><%= date(pedido.fecha_alta) %></td>
                      <td><%= pedido.cliente.nombre_empresa %></td>
                      <td>
                        <%= neumatico.marca %>
                      </td>
                      <td>
                        <%= neumatico.modelo %>
                        <%= neumatico.caracteristica_1 %>
                        <%= neumatico.caracteristica_2 %>
                        <%= neumatico.caracteristica_3 %>
                      </td>
                      <td class="hidden-xs">
                        <%= neumatico.anchura %>/<%= neumatico.altura %>
                        /<%= neumatico.diametro %> <%= neumatico.carga %> <%= neumatico.velocidad %>
                      </td>
                      <td>
                        <%= neumatico.unidades %>
                      </td>
                      <td class="actions">
                        <div class="action-buttons">
                          <a class="table-actions" href="#"><i class="fa fa-print"></i></a>
                          <a class="table-actions" href="#"><i class="fa fa-check"></i></a>
                        </div>
                      </td>
                <% end %>
                </tr>
            <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- end DataTables Example -->
</div>

</div>

</div>

app/views/admin/expedicion_pendientes.html.erb
<div class="container-fluid main-content">
  <div class="page-title">
    <h1>
      Neumaticos
    </h1>
  </div>
  <!-- DataTables Example -->
  <div class="row">
    <div class="col-lg-12">
      <div class="widget-container fluid-height clearfix">
        <div class="heading">
          <i class="fa fa-table"></i>Listado de los Neumáticos Pendientes de entrar a almacén
        </div>
        <div class="widget-content padded clearfix">
          <table class="table table-bordered table-striped" id="EXdataTableCatalog">
            <thead>
            <th>
              # Pedido
            </th>
            <th>
              Fecha
            </th>
            <th class="hidden-xs">
              Cliente
            </th>
            <th class="hidden-xs">
              Marca
            </th>
            <th>
              Modelo
            </th>
            <th>
              Dimensiones
            </th>
            <th>
              Unidades
            </th>
            <th>
              Acciones
            </th>
            </thead>
            <tbody>


            <% @pedidos.each do |pedido| %>

                <% pedido.pedido_detalles.each do |neumatico| %>
                    <tr>
                      <td><%= pedido.id %></td>
                      <td><%= date(pedido.fecha_alta) %></td>
                      <td><%= pedido.cliente.nombre_empresa %></td>
                      <td>
                        <%= neumatico.marca %>
                      </td>
                      <td>
                        <%= neumatico.modelo %>
                        <%= neumatico.caracteristica_1 %>
                        <%= neumatico.caracteristica_2 %>
                        <%= neumatico.caracteristica_3 %>
                      </td>
                      <td class="hidden-xs">
                        <%= neumatico.anchura %>/<%= neumatico.altura %>
                        /<%= neumatico.diametro %> <%= neumatico.carga %> <%= neumatico.velocidad %>
                      </td>
                      <td>
                        <%= neumatico.unidades %>
                      </td>
                      <td class="actions">
                        <div class="action-buttons">
                          <a class="table-actions" href="#"><i class="fa fa-check"></i></a>
                        </div>
                      </td>
                <% end %>
                </tr>
            <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- end DataTables Example -->
</div>

</div>

</div>

app/views/admin/inicio.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="widget-container fluid-height clearfix">
      <div class="heading">
        <i class="fa fa-table"></i>Inicio
      </div>

      <div class="col-lg-12">
        <div class="jumbotron"> No hay ningun contenido definido</div>
      </div>
      <div class="row"> </div>


    </div>
  </div>
</div>

<div class="row"> </div>

app/views/admin/neumaticos.html.erb
<div class="page-title">
  <h1>
    Neumáticos
  </h1>
</div>

<div class="row">
<div class="col-lg-12">
<div class="widget-container fluid-height">
<div class="heading tabs">
  <i class="fa fa-filter"></i>Filtros
  <ul class="nav nav-tabs pull-right" data-tabs="tabs" id="tabs">
    <li class="active">
      <a data-toggle="tab" href="components.html#tab3"><i class="fa fa-road"></i><span>Turismo</span></a>
    </li>
    <li class="">
      <a data-toggle="tab" href="components.html#tab4"><i class="fa fa-circle"></i><span>Moto</span></a>
    </li>
    <li class="">
      <a data-toggle="tab" href="components.html#tab2"><i class="fa fa-truck"></i><span>Camión</span></a>
    </li>
    <li class="">
      <a data-toggle="tab" href="components.html#tab1"><i class="fa fa-leaf"></i><span>Agricola</span></a>
    </li>

  </ul>
</div>
<div class="tab-content padded" id="my-tab-content">
<div class="tab-pane" id="tab4">
  <h3>
    Moto
  </h3>
  <p>
    No implementado
  </p>
</div>
<div class="tab-pane" id="tab1">
  <h3>
    Agrícola
  </h3>

  <p>
    No implementado
  </p>
</div>
<div class="tab-pane" id="tab2">
  <h3>
    Camión
  </h3>

  <p>
    No implementado
  </p>
</div>
<div class="tab-pane active" id="tab3">
<h3>
  Filtros para Turismo
</h3>

<div class="row">
  <form accept-charset="UTF-8" action="/taller/neumaticos" class="form-horizontal" id="filtros" method="post"><div style="display:none"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="y0o8GkhG9YgToq8Q8GopIqd0MymLpEcR6rQWUsszkNM="></div>

    <div class="col-md-2">
      <label class="control-label">Anchura</label>
      <select class="form-control" id="filtros_anchura" name="filtros[anchura]"><option value="7.5">7.5</option>
        <option value="18">18</option>
        <option value="30">30</option>
        <option value="135">135</option>
        <option value="145">145</option>
        <option value="155">155</option>
        <option value="165">165</option>
        <option value="175">175</option>
        <option value="180">180</option>
        <option value="185">185</option>
        <option selected="selected" value="195">195</option>
        <option value="205">205</option>
        <option value="215">215</option>
        <option value="225">225</option>
        <option value="235">235</option>
        <option value="245">245</option>
        <option value="255">255</option>
        <option value="265">265</option>
        <option value="275">275</option>
        <option value="285">285</option>
        <option value="315">315</option></select>
    </div>

    <div class="col-md-2">
      <label class="control-label">Altura</label>
      <select class="form-control" id="filtros_altura" name="filtros[altura]"><option value=""></option>
        <option value="9,5">9,5</option>
        <option value="30">30</option>
        <option value="35">35</option>
        <option value="40">40</option>
        <option value="45">45</option>
        <option value="50">50</option>
        <option value="55">55</option>
        <option value="58">58</option>
        <option value="60">60</option>
        <option selected="selected" value="65">65</option>
        <option value="70">70</option>
        <option value="75">75</option>
        <option value="80">80</option>
        <option value="85">85</option></select>
    </div>

    <div class="col-md-2">
      <label class="control-label">Diametro</label>
      <select class="form-control" id="filtros_diametro" name="filtros[diametro]"><option value="12">12</option>
        <option value="13">13</option>
        <option value="14">14</option>
        <option selected="selected" value="15">15</option>
        <option value="16">16</option>
        <option value="17">17</option>
        <option value="18">18</option>
        <option value="19">19</option>
        <option value="20">20</option>
        <option value="22">22</option></select>
    </div>
  </form></div>
<div class="row">
  <div class="col-md-2">
    <label class="control-label">Marca</label>
    <select class="form-control" id="filtros_marca" name="filtros[marca]"><option value="">Todos</option>
      <option value="ACHILLES">Achilles</option>
      <option value="AVON">Avon</option>
      <option value="BARUM">Barum</option>
      <option value="BFGOODRICH">Bfgoodrich</option>
      <option value="BRIDGESTONE">Bridgestone</option>
      <option value="CONTINENTAL">Continental</option>
      <option value="COOPER">Cooper</option>
      <option value="DOUBLESTAR">Doublestar</option>
      <option value="DUNLOP">Dunlop</option>
      <option value="EFFIPLUS">Effiplus</option>
      <option value="EPTYRES">Eptyres</option>
      <option value="EVERGREEN">Evergreen</option>
      <option value="FEDIMA">Fedima</option>
      <option value="FIRESTONE">Firestone</option>
      <option value="FULDA">Fulda</option>
      <option value="GAJAH TUNGGAL">Gajah tunggal</option>
      <option value="GENERAL">General</option>
      <option value="GERUTTI">Gerutti</option>
      <option value="GOODYEAR">Goodyear</option>
      <option value="HANKOOK">Hankook</option>
      <option value="INFINITY">Infinity</option>
      <option value="INTERSTATE">Interstate</option>
      <option value="KELLY">Kelly</option>
      <option value="KINGSTAR">Kingstar</option>
      <option value="KLEBER">Kleber</option>
      <option value="KUMHO">Kumho</option>
      <option value="LANDSAIL/DELINTE">Landsail/delinte</option>
      <option value="MABOR">Mabor</option>
      <option value="MARSHAL">Marshal</option>
      <option value="MASTER CRAFT">Master craft</option>
      <option value="MASTER-STEEL">Master-steel</option>
      <option value="METEOR">Meteor</option>
      <option value="METZELER">Metzeler</option>
      <option value="MICHELIN">Michelin</option>
      <option value="MILESTONE">Milestone</option>
      <option value="NANKANG">Nankang</option>
      <option value="NEXEN">Nexen</option>
      <option value="PIRELLI">Pirelli</option>
      <option value="REGAL">Regal</option>
      <option value="ROADSTONE">Roadstone</option>
      <option value="TOYO">Toyo</option>
      <option value="TYFOON">Tyfoon</option>
      <option value="UNIROYAL">Uniroyal</option>
      <option value="VREDESTEIN">Vredestein</option>
      <option value="WANLI">Wanli</option>
      <option value="WESTLAKE">Westlake</option>
      <option value="YOKOHAMA">Yokohama</option></select>
  </div>


  <div class="col-md-2">
    <label class="control-label">Carga</label>
    <select class="form-control" id="filtros_carga" name="filtros[carga]"><option value="">Todos</option>
      <option value="0">0</option>
      <option value="70">70</option>
      <option value="71">71</option>
      <option value="72">72</option>
      <option value="73">73</option>
      <option value="74">74</option>
      <option value="75">75</option>
      <option value="77">77</option>
      <option value="78">78</option>
      <option value="79">79</option>
      <option value="80">80</option>
      <option value="81">81</option>
      <option value="82">82</option>
      <option value="83">83</option>
      <option value="84">84</option>
      <option value="85">85</option>
      <option value="86">86</option>
      <option value="87">87</option>
      <option value="88">88</option>
      <option value="89">89</option>
      <option value="90">90</option>
      <option value="91">91</option>
      <option value="92">92</option>
      <option value="93">93</option>
      <option value="94">94</option>
      <option value="95">95</option>
      <option value="96">96</option>
      <option value="97">97</option>
      <option value="98">98</option>
      <option value="99">99</option>
      <option value="100">100</option>
      <option value="101">101</option>
      <option value="102">102</option>
      <option value="103">103</option>
      <option value="104">104</option>
      <option value="105">105</option>
      <option value="106">106</option>
      <option value="107">107</option>
      <option value="108">108</option>
      <option value="109">109</option>
      <option value="110">110</option>
      <option value="111">111</option>
      <option value="112">112</option>
      <option value="113">113</option>
      <option value="114">114</option>
      <option value="115">115</option>
      <option value="116">116</option>
      <option value="117">117</option>
      <option value="118">118</option>
      <option value="120">120</option>
      <option value="121">121</option>
      <option value="123">123</option></select>
  </div>

  <div class="col-md-2">
    <label class="control-label">Velocidad</label>
    <select class="form-control" id="filtros_velocidad" name="filtros[velocidad]"><option value="%%%">Todas</option>
      <option value="Y">Y - 300 km/h</option>
      <option value="W">W - 270 km/h</option>
      <option value="ZR">ZR - 240 km/h</option>
      <option value="Z">Z - 240 km/h</option>
      <option value="V">V - 240 km/h</option>
      <option value="H">H - 210 km/h</option>
      <option value="T">T - 190 km/h</option>
      <option value="S">S - 180 km/h</option>
      <option value="R">R - 170 km/h</option>
      <option value="Q">Q - 160 km/h</option>
      <option value="P">P - 150 km/h</option>
      <option value="N">N - 140 km/h</option>
      <option value="M">M - 130 km/h</option>
      <option value="L">L - 120 km/h</option>
      <option value="K">K - 110 km/h</option>
      <option value="J">J - 100 km/h</option></select>
  </div>

  <div class="col-md-2">
    <label class="control-label">Temporada</label>
    <select class="form-control" id="filtros_temporada" name="filtros[temporada]"><option value="">Todos</option>
      <option value="Invierno">Invierno</option>
      <option value="Verano">Verano</option>
      <option value="Todo tiemp">Todo Tiempo</option></select>
  </div>

  <div class="col-md-2">
    <label class="control-label">Entega</label>
    <select class="form-control" id="filtros_entrega" name="filtros[entrega]"><option value="">Todos</option>
      <option value="1">Inmediata</option>
      <option value="2">24/48Hs</option></select>
  </div>

  <div class="col-md-2">
    <button style="margin-top:25px;" type="submit" class="btn btn-primary ladda-button form-control" data-style="contract">
      <i class="fa fa-search"></i> Buscar
    </button>
  </div>


</div>

</div>
</div>
</div>
</div>
</div>

<div class="row">

</div>


<!-- /FILTROS COCHE -->

<div class="container-fluid main-content">
  <!-- DataTables Example -->
  <div class="row">
    <div class="col-lg-12">
      <div class="widget-container fluid-height clearfix">
        <div class="heading">
          <i class="fa fa-table"></i>Se han encontrado 0 coincidencias.
        </div>
        <div class="widget-content padded clearfix">
          <table class="table">
            <thead>
            <tr><th>

            </th>
              <th>
                Marca
              </th>
              <th>
                Modelo
              </th>
              <th class="hidden-xs">
                Medidas
              </th>
              <th>
                Caracteristicas
              </th>
              <th>
                Stock
              </th>
              <th>
                PVP
              </th>
              <th></th>
            </tr></thead>
            <tbody>



            </tbody>
          </table>

          <div class="alert alert-warning">
            <button class="close" data-dismiss="alert" type="button">×</button>
            No Hay neumaticos que coincidan con la seleccion actual.
          </div>

        </div>
      </div>
    </div>
  </div>
  <!-- end DataTables Example -->
</div>

app/views/admin/talleres.html.erb
<div class="container-fluid main-content">
  <div class="page-title">
    <h1>
      Talleres
    </h1>
  </div>
  <!-- DataTables Example -->
  <div class="row">
    <div class="col-lg-12">
      <div class="widget-container fluid-height clearfix">
        <div class="heading">
          <i class="fa fa-table"></i> Listando todos los talleres
        </div>
        <div class="widget-content padded clearfix">

          <table class="table table-bordered table-striped" id="dataTable1">
            <thead>
            <th>
              Nombre
            </th>
            <th>
              Telefono
            </th>
            <th class="hidden-xs">
              Movil
            </th>
            <th class="hidden-xs">
              Email
            </th>
            <th class="hidden-xs">

            </th>
            </thead>
            <tbody>
            <% @clientes.each do |cliente| %>
                <tr>
                  <td>
                    <%= cliente.nombre_empresa %>
                  </td>
                  <td>
                    <%= cliente.telefono %>
                  </td>
                  <td class="hidden-xs">
                    <%= cliente.movil %>
                  </td>
                  <td class="hidden-xs">
                    <%= cliente.email %>
                  </td>
                  <td class="hidden-xs">
                    <div class="btn-group">

                      <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Acciones<span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <li>
                          <a href="<%= admin_preferencias_path %>"><i class="fa fa-eye"></i> Ver</a>
                        </li>
                        <li>
                          <a href="<%= admin_preferencias_path %>"><i class="fa fa-edit"></i> Modificar</a>
                        </li>
                        <li>
                          <a href="#"><i class="fa fa-shopping-cart"></i> Pedidos</a>
                        </li>
                      </ul>
                    </div>

                  </td>
                </tr>
            <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- end DataTables Example -->
</div>