config/routes.rb
Rails.application.routes.draw do

  mount DtsCmsAdmin::Engine, at: "cms"

  root 'login#index'

  ##
  # Customers
  resources :clientes do
    member do
      get "pedidos"
    end
  end
  post  'clientes/seleccionar' => "clientes#seleccionar"
  get  'clientes/:id/seleccionar/:proc' => "clientes#seleccionar"

  ##
  # Orders
  resources :pedidos do
    member do
      get "confirmar"
      get "generar"
    end
  end

  ##
  # Shared
  get 'pedidos' => 'static#orders'
  get 'pedidos/:id'  => 'static#order'

  ##
  # Talleres
  get 'taller/inicio' => 'talleres#index'
  get 'taller/pedido_recibido/:id' => 'talleres#pedido_recibido'
  get 'taller/pedido_montado/:id' => 'talleres#pedido_montado'
  get 'taller/preferencias' => 'talleres#preferencias'
  get 'taller/neumaticos' => 'talleres#neumaticos'
  post 'taller/neumaticos' => 'talleres#neumaticos'
  post 'talleres/suplementos'
  get 'taller/:id/neumatico' => 'talleres#neumatico'

  ##
  # Cart
  get  'carrito' => "shopping_carts#show"
  post 'carrito/modificar/:id' => "shopping_carts#modify"
  get  'carrito/eliminar/:id' => "shopping_carts#remove"
  get  'carrito/vaciar' => "shopping_carts#clear"
  get  'carrito/guardar_como_presupuesto' => "shopping_carts#save_as_bugdet"
  get  'carrito/eliminar_presupuesto/:id' => "shopping_carts#destroy_budget"

  ##
  # acts_as_cart routes
  resource :shopping_cart


  ##
  # Proveedores

  # almacen
  get "almacen/inicio"
  get "almacen/pendientes"
  get "almacen/enviados"

  #gerencia
  get "gerencia/inicio"
  get "gerencia/listados"

  #financiero
  get "financiero/inicio"
  get "financiero/distribuidores"
  get "financiero/clientes"
  get "financiero/historico"

  #admin
  get "admin/inicio"
  get "admin/neumaticos"
  get "admin/distribuidores"
  get "admin/talleres"
  get "admin/pedidos"
  get "admin/preferencias"
  get "admin/web"
  get "admin/expedicion_listado"
  get "admin/expedicion_pendientes"
  get "admin/expedicion_enviados"

  #comercial

  get "comercial/neumaticos"
  get 'comercial/:id/neumatico' => 'comercial#neumatico'
  post "comercial/neumaticos"

  ##
  # Login

  get  "login/index"
  post "login/index"

  ##
  # Web Design
  get "web/selector"
  post "web/selector"

end

app/views/web/selector.html.erb
<%= form_tag(web_selector_path, :method => 'post', :multipart => true) do %>
    <div class="col-lg-12">
    <div class="widget-container fluid-height">
    <div class="heading tabs">
      <i class="fa fa-gears"></i>Opciones
      <ul class="nav nav-tabs pull-right" data-tabs="tabs" id="tabs">
        <li class="active">
          <a data-toggle="tab" href="components.html#template"><i class="fa fa-pencil"></i><span>Estético</span></a>
        </li>
        <li>
          <a data-toggle="tab" href="components.html#ecommerce"><i class="fa fa-sitemap"></i><span>Funcional</span></a>
        </li>
        <li>
        <a data-toggle="tab" href="components.html#contenidos"><i class="fa fa-edit"></i><span>Contenidos</span></a>
        </li>
      </ul>
    </div>
    <div class="tab-content padded" id="my-tab-content">
      <div class="tab-pane active" id="template">
        <div class="page-title">
          <h1>
            Diseño
          </h1>
        </div>

        <div class="row">
            <div class="col-md-4">
              <div class="widget-container fluid-height">
                <div class="heading">
                  <i class="fa fa-desktop"></i>Modelo 1 - &quot;Full Width&quot;
                </div>
                <div class="widget-content padded text-center">
                  <a class="trigger" data-picture="/images/web/home-full-width.jpg" data-title="Home - Modelo 1 Full Widht"><img src="/assets/layout-home-1.png" class="img-responsive"></a>
                  <br><br>
                  <label class="radio" for="home_default">

                    <%= radio_button_tag 'home', 'default', nil, id: "home_default", checked: (@prefs.home == "default" ? true : false) %>

                    <span>Estilo 1</span></label>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="widget-container fluid-height">
                <div class="heading">
                  <i class="fa fa-desktop"></i>Modelo 2 - &quot;Boxed&quot;
                </div>
                <div class="widget-content padded text-center">
                  <a class="trigger" data-picture="/images/web/home-boxed.jpg" data-title="Home - Modelo 2 Boxed"><img src="/assets/layout-home-2.png" class="img-responsive"></a>
                  <br><br>
                  <label class="radio" for="home_2">
                    <%= radio_button_tag 'home', '2', nil, id: "home_2", checked: (@prefs.home == "2" ? true : false) %>
                    <span>Estilo 2</span></label>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="widget-container fluid-height">
                <div class="heading">
                  <i class="fa fa-desktop"></i>Modelo 3 - &quot;Boxed Simple&quot;
                </div>
                <div class="widget-content padded text-center">
                  <a class="trigger" data-picture="/images/web/home-boxed-simple.jpg" data-title="Home - Modelo 2 Boxed Simple"><img src="/assets/layout-home-3.png" class="img-responsive">
                  </a>
                  <br><br>
                  <label class="radio" for="home_3">
                    <%= radio_button_tag 'home', '3', nil, id: "home_3", checked: (@prefs.home == "3" ? true : false) %>
                    <span>Estilo 3</span></label>
                </div>
              </div>
            </div>

        </div>
        <div class="row">
          <hr/>
          <h2>Personalizacion</h2>

          <div class="col-md-4">
            <div class="form-group">

              <label class="control-label col-md-4 pull" for="nombre">Color primario</label>

              <div class="col-md-7">
                <div class="input-group color" data-color="rgb(84, 184, 178)" data-color-format="rgb" id="cp3">
                  <input class="form-control" readonly="" type="text" value="rgb(84, 184, 178)"><span class="input-group-addon"><i style="background-color: rgb(84, 184, 178)"></i></span></input>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label class="control-label col-md-5" for="nombre">Color Secundario</label>

              <div class="col-md-7">
                <div class="input-group color" data-color="rgb(55, 135, 130)" data-color-format="rgb" id="cp4">
                  <input class="form-control" readonly="" type="text" value="rgb(55, 135, 130)"><span class="input-group-addon"><i style="background-color: rgb(55, 135, 130)"></i></span></input>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <div class="col-md-6 pull-right">
                <a class="btn btn-info-outline" href="http://demo.dev?view=1_2" target="_blank"><i class="fa fa-search-plus"></i>
                  Previsualización</a>
              </div>
            </div>
          </div>

          <br/>
          <br/>
          <hr/>
          <button class="btn btn-success-outline form-control" type="submit"><i class="fa fa-save"></i> Guardar los cambios  </button>

        </div>

      </div>
      <div class="tab-pane" id="ecommerce">

        <div class="container-fluid main-content">
          <div class="page-title">
            <h1>
              Listado de neumaticos
            </h1>
          </div>
          <div class="row">
              <div class="col-md-6">
                <div class="widget-container fluid-height">
                  <div class="heading">
                    <i class="fa fa-desktop"></i>Modelo 1
                  </div>
                  <div class="widget-content padded text-center">
                    <a class="trigger" data-picture="/images/web/categoria-modelo-1.jpg" data-title="Categoria - Modelo 1"><img src="/assets/layout-cat-1.png"></a>
                    <br><br>
                    <label class="radio" for="listado_default">
                      <%= radio_button_tag 'listado', '', nil, id: "listado_default", checked: (@prefs.listado == "default" ? true : false) %>
                      <span>Estilo 1</span></label>
                    <em>Barra de opciones y filtros a la izquierda. <br>Encabezado con imagen y subcategorías</em>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="widget-container fluid-height">
                  <div class="heading">
                    <i class="fa fa-desktop"></i>Modelo 2
                  </div>
                  <div class="widget-content padded text-center">
                    <a class="trigger" data-picture="/images/web/categoria-modelo-2.jpg" data-title="Categoria - Modelo 2"><img src="/assets/layout-cat-2.png"></a>
                    <br><br>
                    <label class="radio" for="listado_alt">
                      <%= radio_button_tag 'listado', 'alt', nil, id: "listado_alt", checked: (@prefs.listado == "alt" ? true : false) %>
                      <span>Estilo 2</span></label>
                    <em>Barra de opciones y filtros a la derecha. <br>Sin imagen de encabezado</em>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>

        <div class="container-fluid main-content">
          <div class="page-title">
            <h1>
              Detalle del neumatico
            </h1>
          </div>
          <div class="row">
              <div class="col-md-4">
                <div class="widget-container fluid-height">
                  <div class="heading">
                    <i class="fa fa-desktop"></i>Modelo 1
                  </div>
                  <div class="widget-content padded text-center">
                    <a class="trigger" data-picture="/images/web/producto-modelo-1.jpg" data-title="Productos - Modelo 1"><img src="/assets/layout-prod-1.png" class="img-responsive"></a>
                    <br><br>
                    <label class="radio" for="detalle_default"><%= radio_button_tag 'detalle', '', nil, id: "detalle_default", checked: (@prefs.detalle == "default" ? true : false) %><span>Estilo 1</span></label>
                    <em>Ficha ancho completo.</em>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="widget-container fluid-height">
                  <div class="heading">
                    <i class="fa fa-desktop"></i>Modelo 2
                  </div>
                  <div class="widget-content padded text-center">
                    <a class="trigger" data-picture="/images/web/producto-modelo-2.jpg" data-title="Productos - Modelo 2"><img src="/assets/layout-prod-2.png" class="img-responsive"></a>
                    <br><br>
                    <label class="radio" for="detalle_alt"><%= radio_button_tag 'detalle', 'alt', nil, id: "detalle_alt", checked: (@prefs.detalle == "alt" ? true : false) %><span>Estilo 2</span></label>
                    <em>Ficha con columna izquierda para contenidos secundarios.</em>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="widget-container fluid-height">
                  <div class="heading">
                    <i class="fa fa-desktop"></i>Modelo 3
                  </div>
                  <div class="widget-content padded text-center">
                    <a class="trigger" data-picture="/images/web/producto-modelo-3.jpg" data-title="Productos - Modelo 3"><img src="/assets/layout-prod-3.png" class="img-responsive"></a>
                    <br><br>
                    <label class="radio" for="detalle_alt1"><%= radio_button_tag 'detalle', 'alt1', nil, id: "detalle_alt1", checked: (@prefs.detalle == "alt1" ? true : false) %><span>Estilo 3</span></label>
                    <em>Ficha con columna derecha para contenidos secundarios.</em>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>

        <button class="btn btn-success-outline form-control " type="submit"><i class="fa fa-save"></i> Guardar los cambios  </button>

      </div>

      <div class="tab-pane" id="contenidos">
        <h3>
          Contenidos
        </h3>

        <button class="btn btn-lg btn-block btn-default-outline">Home</button>
        <a href="http://demo.dev/editor/quienes-somos" target="_blank" class="btn btn-lg btn-block btn-primary-outline">Quienes somos</a>
        <a href="http://demo.dev/editor/equipo" target="_blank" class="btn btn-lg btn-block btn-primary-outline">Equipo</a>
        <button class="btn btn-lg btn-block btn-default-outline">Donde estamos</button>
        <button class="btn btn-lg btn-block btn-default-outline">Tienda online</button>
        <button class="btn btn-lg btn-block btn-default-outline">Contacto</button>


      </div>

    </div>
    </div>
    </div>
<% end %>






<!--MODAL SETUP-->
<div class="modal fade " id="myModal" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
        <h4 class="modal-title">
          Coso
        </h4>
      </div>
      <div class="modal-body">
        <img src="" class="img-responsive" id="image-holder">
      </div>
      <div class="modal-footer">
        <button class="btn btn-default-outline" data-dismiss="modal" type="button">Cerrar</button>
      </div>
    </div>
  </div>
</div>


<script>
    $('.trigger').click(function () {
        // Send the src on click of button to the iframe. Which will make it load.
        var picture = $(this).data("picture");
        var title = $(this).data("title");
        $("#image-holder").attr("src", picture);
        $(".modal-title").text(title);
        $('.modal').modal({show: true});
        // Hide the loading message

    })
</script>